apiVersion: batch/v1
kind: CronJob
metadata:
  name: mongodb-backup
  namespace: ds-project
spec:
  schedule: {{ .Values.backupContainer.schedule }}  # This schedules the job to run daily at 2am
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: backup
            image: {{ .Values.backupContainer.repository }}:{{ .Values.backupContainer.tag }}
            command:
            - /bin/sh
            - -c
            - >
              mongodump --host mongodb --db DATABASE_NAME_HERE --out /backup/$(date +\%F-\%T) &&
              tar -czf /backup/backup-$(date +\%F-\%T).tar.gz /backup/$(date +\%F-\%T) &&
              rm -rf /backup/$(date +\%F-\%T)
            volumeMounts:
            - name: {{ .Values.backupVolume.name }}
              mountPath: {{ .Values.backupVolume.mountPath }}
          restartPolicy: OnFailure
          volumes:
          - name: {{ .Values.backupVolume.name }}
            persistentVolumeClaim:
              claimName: mongodb-pvc
