apiVersion: autoscaling/v
kind: HorizontalPodAutoscaler
metadata:
  name: backend-hpa
  namespace: ds-project
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: backend
  minReplicas: 2
  maxReplicas: 6
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
